# Generated by Django 5.1.3 on 2025-05-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laborantin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstApp.utilisateur')),
            ],
            bases=('firstApp.utilisateur',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstApp.utilisateur')),
                ('numero_carte_identite', models.CharField(max_length=50, unique=True)),
            ],
            bases=('firstApp.utilisateur',),
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstApp.utilisateur')),
            ],
            bases=('firstApp.utilisateur',),
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstApp.utilisateur')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.specialite')),
            ],
            bases=('firstApp.utilisateur',),
        ),
    ]
