# Generated by Django 5.1.3 on 2025-05-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_utilisateur_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstApp.utilisateur')),
            ],
            bases=('firstApp.utilisateur',),
        ),
    ]
