# Generated by Django 5.1.3 on 2025-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
