# Generated by Django 5.1.3 on 2025-05-29 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_utilisateur_is_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.patient')),
            ],
        ),
    ]
