# Generated by Django 5.1.3 on 2025-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_dossierpatient_pagedossierpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedossierpatient',
            name='resume_consultation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
