# Generated by Django 5.1.3 on 2025-06-18 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0007_dossierpatient_pagedossierpatient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_group", models.BooleanField(default=False)),
                ("nom_groupe", models.CharField(blank=True, max_length=100, null=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to="firstApp.utilisateur"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                ("date_envoi", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="firstApp.conversation",
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstApp.utilisateur",
                    ),
                ),
                (
                    "lu_par",
                    models.ManyToManyField(
                        blank=True,
                        related_name="messages_lus",
                        to="firstApp.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("lien", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("lu", models.BooleanField(default=False)),
                ("type", models.CharField(default="info", max_length=50)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="firstApp.utilisateur",
                    ),
                ),
            ],
        ),
    ]
