# Generated by Django 5.1.3 on 2025-06-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0008_conversation_message_notification"),
        ("firstApp", "0008_pagedossierpatient_resume_consultation"),
    ]

    operations = []
