# Generated by Django 5.1.3 on 2025-06-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0009_merge_20250620_0053"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="destinataire",
        ),
        migrations.AddField(
            model_name="notification",
            name="destinataires",
            field=models.ManyToManyField(
                related_name="notifications", to="firstApp.utilisateur"
            ),
        ),
    ]
