# Generated by Django 5.1.3 on 2025-06-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0010_remove_notification_destinataire_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="destinataires",
            new_name="destinataire",
        ),
    ]
