# Generated by Django 5.1.3 on 2025-06-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0011_rename_destinataires_notification_destinataire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="destinataire",
        ),
        migrations.AddField(
            model_name="notification",
            name="destinataire",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="firstApp.utilisateur",
            ),
            preserve_default=False,
        ),
    ]
