# Generated by Django 5.1.3 on 2025-06-22 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_remove_notification_destinataire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(blank=True, max_length=255)),
                ('soins', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_agent', to='firstApp.utilisateur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_patient', to='firstApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='firstApp.facture')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.service')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.TextField()),
                ('ligne_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='firstApp.lignefacture')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_medicaments', models.TextField()),
                ('posologie', models.TextField()),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='firstApp.resultat')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='services',
            field=models.ManyToManyField(through='firstApp.LigneFacture', to='firstApp.service'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstApp.typefacture'),
        ),
    ]
