# Generated by Django 5.1.3 on 2025-06-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_service_typefacture_facture_lignefacture_resultat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon (secrétaire)'), ('validee', 'Validée (médecin)'), ('attente_secretaire', 'En attente secrétaire'), ('attente_laborantin', 'En attente laborantin'), ('attente_medecin', 'En attente médecin'), ('cloturee', 'Clôturée')], default='brouillon', max_length=30),
        ),
    ]
