# Generated by Django 5.1.3 on 2025-06-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0015_utilisateur_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="user",
        ),
    ]
