# Generated by Django 5.1.3 on 2025-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0016_remove_utilisateur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedossierpatient',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagedossierpatient',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
