# Generated by Django 5.1.3 on 2025-07-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0017_pagedossierpatient_motif_pagedossierpatient_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierpatient',
            name='document_joint',
            field=models.FileField(blank=True, null=True, upload_to='dossiers/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='fichier_prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='fichier_resultat',
            field=models.FileField(blank=True, null=True, upload_to='resultats/'),
        ),
    ]
