# Generated by Django 5.1.3 on 2025-08-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0018_dossierpatient_document_joint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
